name: mmapper
version: 2.6.0+git
version-script: git describe --tags --always --long
icon: src/resources/icons/m.png
summary: MUME Mapper
description: |
  MMapper is a graphical mapper for a MUD named MUME (Multi-Users in Middle
  Earth). The game is traditionally played in a text-only mode, but MMapper tries
  to represent the virtual world in user-friendly graphical environment. It acts
  as a proxy between a telnet client and a MUD server, being able to analyze game
  data in real time and show player's position in a map.

grade: stable
confinement: strict
base: core18

apps:
  mmapper-desktop:
    command: desktop-launch mmapper
    desktop: usr/share/applications/org.mume.MMapper.desktop
    plugs:
      - home
      - gsettings
      - network
      - network-bind
      - opengl
      - x11
      - desktop
      - desktop-legacy
      - unity7
    environment:
      DISABLE_WAYLAND: 1

parts:
  mmapper:
    plugin: cmake
    source: .
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DWITH_UPDATER=false
    build-packages:
      - build-essential
      - zlib1g-dev
      - libssl-dev
      - qtbase5-dev
      - libqt5opengl5-dev
      - qttools5-dev-tools
      - libminiupnpc-dev
    stage-packages:
      - zlib1g
      - libssl1.1
      - qtwayland5
      - libminiupnpc10
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=org.mume.MMapper|Icon=${SNAP}/usr/share/icons/hicolor/256x256/apps/org.mume.MMapper.png|g' $SNAPCRAFT_PART_INSTALL/usr/share/applications/org.mume.MMapper.desktop
    after: [desktop-qt5]
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - locales-all
      - xdg-user-dirs
