name: mmapper
adopt-info: mmapper
icon: src/resources/icons/m-release.png
summary: MUME Mapper
license: GPL-2.0-or-later
description: |
  MMapper is a graphical mapper for a MUD named MUME (Multi-Users in Middle
  Earth). The game is traditionally played in a text-only mode, but MMapper tries
  to represent the virtual world in a user-friendly graphical environment. It acts
  as a proxy between a telnet client and a MUD server, being able to analyze game
  data in real time and show the player's position on a map.

grade: stable
confinement: strict
base: core24
compression: lzo

platforms:
  amd64:
  arm64:

apps:
  mmapper:
    command: usr/bin/mmapper
    common-id: org.mume.MMapper
    desktop: usr/share/applications/org.mume.MMapper.desktop
    extensions:
      - kde-neon-6
    plugs:
      - home
      - network
      - network-bind
      - opengl

parts:
  mmapper:
    parse-info:
      - usr/share/metainfo/org.mume.MMapper.xml
    build-snaps:
      - kde-qt6-core24-sdk/latest/stable
      - kf6-core24-sdk/latest/stable
    plugin: cmake
    source: .
    source-type: local
    cmake-generator: Ninja
    cmake-parameters:
      - -DPACKAGE_TYPE=Snap
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DWITH_UPDATER=OFF
      - -DWITH_WEBSOCKET=ON
      - -DWITH_QTKEYCHAIN=ON
      - -DUSE_MOLD=ON
      - -DCMAKE_INSTALL_SYSCONFDIR=/etc
      - -DCMAKE_INSTALL_LOCALSTATEDIR=/var
      - -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF
      - -DCMAKE_INSTALL_RUNSTATEDIR=/run
      - -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON
      - -DCMAKE_VERBOSE_MAKEFILE=ON
      - -DCMAKE_INSTALL_LIBDIR=lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - --log-level=STATUS
      - -DCMAKE_LIBRARY_PATH=lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
    build-packages:
      - libglm-dev
      - libssl-dev
      - zlib1g-dev
      - mold
    stage-packages:
      - libssl3t64
      - zlib1g
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --always --long --exclude beta | sed 's/^v//')
    override-build: |
      craftctl default
      sed -i 's|Icon=org.mume.MMapper|Icon=${SNAP}/usr/share/icons/hicolor/256x256/apps/org.mume.MMapper.png|g' $CRAFT_PART_INSTALL/usr/share/applications/org.mume.MMapper.desktop
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/doc/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
  gpu-2404:
    after: [mmapper]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - mmapper
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done
