title: Play MUME with MMapper
description: MMapper is a mud mapper especially written for the mud MUME
logo: https://raw.githubusercontent.com/MUME/MMapper/master//src/resources/icons/hi256-app-mmapper-release.png
screenshot: https://raw.githubusercontent.com/MUME/MMapper/master/appdata/screenshot1.png
markdown: kramdown
kramdown:
  toc_levels: 1..2
