# cmake/GenerateQRC.cmake
# Assumes INPUT_DIR and OUTPUT_FILE are passed as -D variables

if(NOT INPUT_DIR)
    message(FATAL_ERROR "INPUT_DIR not specified for GenerateQRC.cmake")
endif()
if(NOT OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE not specified for GenerateQRC.cmake")
endif()

# Find ALL .jpg files recursively within INPUT_DIR and its subdirectories.
# The RELATIVE "${INPUT_DIR}" part ensures that the paths in IMAGE_FILES
# are relative to INPUT_DIR, e.g., "areas/image.jpg" or "subdir/image.jpg".
file(GLOB_RECURSE IMAGE_FILES RELATIVE "${INPUT_DIR}" "${INPUT_DIR}/*.jpg")

# Assuming map files are handled similarly and exist
file(GLOB MAP_FILES RELATIVE "${INPUT_DIR}" "${INPUT_DIR}/arda")

set(RESOURCE_CONTENT "<!-- This file is automatically generated. -->\n<!DOCTYPE RCC>\n<RCC version=\"1.0\">\n  <qresource prefix=\"/\">\n")
foreach(image_file ${IMAGE_FILES})
    string(APPEND RESOURCE_CONTENT "    <file compress-algo=\"none\">${image_file}</file>\n")
endforeach()
foreach(map_file ${MAP_FILES})
    string(APPEND RESOURCE_CONTENT "    <file compress-algo=\"best\">${map_file}</file>\n")
endforeach()
string(APPEND RESOURCE_CONTENT "  </qresource>\n</RCC>\n")

file(WRITE "${OUTPUT_FILE}" "${RESOURCE_CONTENT}")
