name: test-report
on:
  workflow_run:
    workflows: ['build-test']
    types:
      - completed
jobs:
  report:
    name: Test Report
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v2
      with:
        artifact: /test-results (.*)/
        name: Test Report $1
        path: '*.xml'
        reporter: java-junit
